apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms1-frontend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/takuma-8trees/argocd.git
    targetRevision: main
    path: charts/ms1-frontend
    helm:
      valueFiles:
        - ../../environments/dev/ms1-frontend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

